menu:
  nome: "&e>> &6&lWARPS &e<<"
  tamanho: 45
warps:
#[00] [01] [02] [03] [04] [05] [06] [07] [08]
#[09] [10] [11] [12] [13] [14] [15] [16] [17]
#[18] [19] [20] [21] [22] [23] [24] [25] [26]
#[27] [28] [29] [30] [31] [32] [33] [34] [35]
#[36] [37] [38] [39] [40] [41] [42] [43] [44]
  '0':
    item: 291
    nome: teste 1
    itemDesc:
    - ''
    - '&cAltere a desc. na config'
    locais:
    - world;-214;68;400;0.0;0.0
    sistemaPermissao: true
    permissao: pdgh.vip
    msgPermissao:
    - '&6Apenas VIPs podem se teleportar para essa warp.'
    - '&6Mais informações: &fhttp://pdgh.com.br/vip/'